//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public int Id { get; set; }
        public string PostedBy { get; set; }
        public string ItemName { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string Price { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public string Perfomance { get; set; }
        public string Address { get; set; }
        public string Warranty { get; set; }
    }
}
